### ISSUE TITLE
Composição do fundo

### ISSUE THREAD

**Issue by gitbobbed** [alepmaros/monetus-fiavis#1]
Não sei se aqui é o melhor local para postar isso (avisar se não for) mas a composição do FIA mudou, acho que hoje.

De acordo com o site, são as seguintes:

Composição
Natura (NATU3)
12,09%
M. Dias Branco (MDIA3)
11,81%
It Now IBrX-50 (PIBB11)
11,08%
ABC Brasil (ABCB4)
8,77%
Grendene (GRND3)
7,69%
Randon (RAPT4)
7,59%
Via Varejo (VVAR11)
6,55%
Cielo (CIEL3)
5,90%
CVC Brasil (CVCB3)
5,89%
Grazziotin (CGRA3)
4,68%
Portobello (PTBL3)
4,65%
iShares S&P 500 (IVVB11)
4,34%
Eztec (EZTC3)
4,06%
Estácio (ESTC3)
3,58%
Smiles (SMLS3)
1,32%

**Comment by alepmaros** [comment]
Muito obrigado por avisar! Pode ser por aqui sim. Acho que num futuro próximo devo colocar um botao no site pra avisar sobre alterações no fundo de uma maneira mais fácil.

Já foi alterado :)
