### ISSUE TITLE
Composição do fundo

### ISSUE THREAD

**Issue by gitbobbed** [alepmaros/monetus-fiavis#2]
Rapaz, mudaram de novo a composição.

Seguem aí as novas cotações:
M. Dias Branco (MDIA3) 11,14%
Natura (NATU3) 10,98%
It Now IBrX-50 (PIBB11) 10,05%
ABC Brasil (ABCB4) 8,42%
Randon (RAPT4) 7,18%
Grendene (GRND3) 6,90%
Marcopolo (POMO4) 6,49% -> essa é nova e eles não colocaram o ticker, mas tenho 99,8576% de certeza que é esse.
Via Varejo (VVAR11) 6,32%
Grazziotin (CGRA3) 5,89%
CVC Brasil (CVCB3) 5,25%
Cielo (CIEL3) 5,20%
Portobello (PTBL3) 4,23%
iShares S&P 500 (IVVB11) 3,89%
Eztec (EZTC3) 3,66%
Estácio (ESTC3) 3,20%
Smiles (SMLS3) 1,20%

**Comment by Dayrell** [comment]
Obrigado, @gitbobbed. Editei o arquivo.
