### ISSUE TITLE
Destaualizado?

### ISSUE THREAD

**Issue by gitbobbed** [alepmaros/monetus-fiavis#4]
Pessoal, as cotações andaram bem desatualizadas por uns dias, depois aparentemente sincronizaram corretamente, mas hoje o valor está (gloriosamente) superestimado. 

Acho que vcs não tem obrigação nenhuma de manter atualizado, mas será que não vale a pena colocar uma mensagem lá avisando que os dados não estão mais confiáveis? O site acabou ficando bem popular com os clientes do Monetus, e todo dia vejo alguém perguntando no Fb ou WhatsApp sobre o bot ou o site.

Valeu!

Abraço,

Daniel

**Comment by Dayrell** [comment]
Obrigado pelo aviso, Daniel.
Tivemos que mudar a API que usamos para pegar as informações e as coisas ficaram difíceis. Logo vou colocar um aviso no site explicando a situação e os próximos passos.
